Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2021-11, with the labels that each got.

#71 Get GP Practice Cluster data from the Open Data platform
  All_years/01-Macros/Macro-01-Universal.sps
  All_years/02-Lookups/00_get_gp_cluster_data.R
  All_years/02-Lookups/Lookup-02-GP_practice.sps
Labels: back-end

#101 Add nsu
  2019-20/C04 Add on NSU cohort.sps
  2020-21/C04 Add on NSU cohort.sps
  2020-21/D04 Calculate and match Keep population flag.sps
Labels: enhancement, back-end

#104 Add new variables for testing D05X
  2014-15/D05X Individual file tests.sps
  2015-16/D05X Individual file tests.sps
  2016-17/D05X Individual file tests.sps
  2017-18/D05X Individual file tests.sps
  2018-19/D05X Individual file tests.sps
  2019-20/D05X Individual file tests.sps
  2020-21/D05X Individual file tests.sps
  2021-22/D05X Individual file tests.sps
Labels: enhancement, back-end, Dec-21 Update

#108 Change the Social Care demographics extract to SQL
  All_years/02-Lookups/Lookup-05-Social_Care_Demographics.sps
Labels: back-end

#109 Changed the client extract to use SQL
  2017-18/A05 Prepare Social Care Client lookup.sps
  2018-19/A05 Prepare Social Care Client lookup.sps
  2019-20/A05 Prepare Social Care Client lookup.sps
  2020-21/A05 Prepare Social Care Client lookup.sps
Labels: back-end

#105 Adding Social Care to 21/22
  2019-20/C01 Make Episode File.sps
  2020-21/C01 Make Episode File.sps
  2021-22/A05 Prepare Social Care Client lookup.sps
  2021-22/B08X Care Homes tests.sps
  2021-22/B08a Create care home name lookup.sps
  2021-22/B08b Process SOURCE Care Homes.sps
  2021-22/C01 Make Episode File.sps
  All_years/01-Macros/Macro-01-Universal.sps
  All_years/04-Social_Care/02-Care_home_data.sps
  NEWS.md
Labels: Dec-21 Update
