Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2021-08, with the labels that each got.

#53 29 Make new cij_delay variable
  2014-15/C01 Make Episode File.sps
  2014-15/C10 Final tidy for Episode file.sps
  2014-15/D01 Make Individual File.sps
  2014-15/D05 Final tidy for Individual file.sps
  2014-15/D05X Individual file tests.sps
  2015-16/C01 Make Episode File.sps
  2015-16/C10 Final tidy for Episode file.sps
  2015-16/D01 Make Individual File.sps
  2015-16/D05 Final tidy for Individual file.sps
  2015-16/D05X Individual file tests.sps
  2016-17/C02 Link Delayed Discharge episodes.sps
  2016-17/C10 Final tidy for Episode file.sps
  2016-17/D01 Make Individual File.sps
  2016-17/D05 Final tidy for Individual file.sps
  2016-17/D05X Individual file tests.sps
  2017-18/C02 Link Delayed Discharge episodes.sps
  2017-18/C10 Final tidy for Episode file.sps
  2017-18/D01 Make Individual File.sps
  2017-18/D05 Final tidy for Individual file.sps
  2017-18/D05X Individual file tests.sps
  2018-19/C02 Link Delayed Discharge episodes.sps
  2018-19/C10 Final tidy for Episode file.sps
  2018-19/D01 Make Individual File.sps
  2018-19/D05 Final tidy for Individual file.sps
  2018-19/D05X Individual file tests.sps
  2019-20/C02 Link Delayed Discharge episodes.sps
  2019-20/C10 Final tidy for Episode file.sps
  2019-20/D01 Make Individual File.sps
  2019-20/D05 Final tidy for Individual file.sps
  2019-20/D05X Individual file tests.sps
  2020-21/C02 Link Delayed Discharge episodes.sps
  2020-21/C10 Final tidy for Episode file.sps
  2020-21/D01 Make Individual File.sps
  2020-21/D05 Final tidy for Individual file.sps
  2020-21/D05X Individual file tests.sps
Labels: enhancement

#55 Add ppa count
  2014-15/D01 Make Individual File.sps
  2014-15/D05 Final tidy for Individual file.sps
  2014-15/D05X Individual file tests.sps
  2015-16/D01 Make Individual File.sps
  2015-16/D05 Final tidy for Individual file.sps
  2015-16/D05X Individual file tests.sps
  2016-17/D01 Make Individual File.sps
  2016-17/D05 Final tidy for Individual file.sps
  2016-17/D05X Individual file tests.sps
  2017-18/D01 Make Individual File.sps
  2017-18/D05 Final tidy for Individual file.sps
  2017-18/D05X Individual file tests.sps
  2018-19/D01 Make Individual File.sps
  2018-19/D05 Final tidy for Individual file.sps
  2018-19/D05X Individual file tests.sps
  2019-20/D01 Make Individual File.sps
  2019-20/D05 Final tidy for Individual file.sps
  2019-20/D05X Individual file tests.sps
  2020-21/D01 Make Individual File.sps
  2020-21/D05 Final tidy for Individual file.sps
  2020-21/D05X Individual file tests.sps
Labels: enhancement, back-end

#56 Add 2021/22 syntax
  2021-22/A01b Set up 2122 Macros.sps
  2021-22/A05 Prepare Social Care Client lookup.sps
  2021-22/B01 Process Acute (SMR01 and GLS) extract.sps
  2021-22/B01X Acute_tests.sps
  2021-22/B01a Fix C3 costs.sps
  2021-22/B02 Process Maternity (SMR02) extract.sps
  2021-22/B02X Maternity_tests.sps
  2021-22/B03 Process Outpatients (SMR00) extract.sps
  2021-22/B03X Outpatient_tests.sps
  2021-22/B04 Process Mental Health (SMR04) extract.sps
  2021-22/B04X MentalHealth_tests.sps
  2021-22/B05X A&E_tests.sps
  2021-22/B05a Process A&E (AE2) extract.sps
  2021-22/B05b Link CUP marker to A&E.sps
  2021-22/B06 Process PIS extract.sps
  2021-22/B06X PIS_tests.sps
  2021-22/B08X Care Homes tests.sps
  2021-22/B08a Create care home name lookup.sps
  2021-22/B08b Process SOURCE Care Homes.sps
  2021-22/B09X GPOoH_tests.sps
  2021-22/B09a Process GP Out of hours Diagnoses extract.sps
  2021-22/B09b Process GP Out of hours Outcomes extract.sps
  2021-22/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2021-22/B10 Process Delayed Discharge extract.sps
  2021-22/B10X DD_tests.sps
  2021-22/B11 Process Deaths (NRS) extract.sps
  2021-22/B11X NRS_tests.sps
  2021-22/B12 Create CHI - LTC Lookup.sps
  2021-22/B12X CHI-LTC_tests.sps
  2021-22/B15 Process Homelessness extract.sps
  2021-22/B15X Homelessness_tests.sps
  2021-22/C01 Make Episode File.sps
  2021-22/C02 Link Delayed Discharge episodes.sps
  2021-22/C03 Link Homelessness.sps
  2021-22/C04 Add on NSU cohort.sps
  2021-22/C05 Match on LTCs.sps
  2021-22/C06 Death fixes.sps
  2021-22/C07 Calculate pathways cohorts.sps
  2021-22/C08 Match on CHI variables - Cohorts SPARRA and HHG.sps
  2021-22/C09 Match on postcode and gpprac variables.sps
  2021-22/C10 Final tidy for Episode file.sps
  2021-22/C10X Episode file tests.sps
  2021-22/C11 Tidy up files.sps
  2021-22/D01 Make Individual File.sps
  2021-22/D02 Match on postcode and gpprac variables.sps
  2021-22/D03 Calculate and match HRI variables.sps
  2021-22/D04 Calculate and match Keep population flag.sps
  2021-22/D05 Final tidy for Individual file.sps
  2021-22/D05X Individual file tests.sps
  2021-22/D06 Tidy up files.sps
  2021-22/E00 Calculate Anon CHI for new CHIs.sps
  2021-22/E01 Replace CHI with Anon CHI.sps
Labels: back-end
