Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-09, with the labels that each got.

#368 Change IT extract path functions
  NAMESPACE
  R/00-update_refs.R
  R/find_latest_file.R
  R/get_file_paths.R
  R/get_it_extract_paths.R
  man/find_latest_file.Rd
  man/get_dd_period.Rd
  man/get_file_path.Rd
  man/get_it_deaths_path.Rd
  man/get_it_ltc_path.Rd
  man/get_it_prescribing_path.Rd
  man/it_extract_ref.Rd
  man/latest_update.Rd
  man/previous_update.Rd
  tests/testthat/test-00-update_refs.R
  tests/testthat/test-get_it_extract_paths.R
Labels: enhancement

#374 373 remove zsav
  Production_scripts/Create_costs/costs-care_home.R
  Production_scripts/Create_costs/costs-gp_out_of_hours.R
  Production_scripts/Create_costs/costs-home_care.R
  Production_scripts/Create_costs/costs_district_nursing.R
  Production_scripts/Create_slf_lookups/lookup_chi_deaths.R
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
  Production_scripts/Create_slf_lookups/lookup_ltc.R
  Production_scripts/Create_slf_lookups/lookup_postcode.R
  Production_scripts/Process_extracts/extract_a&e.R
  Production_scripts/Process_extracts/extract_acute_incl_gls.R
  Production_scripts/Process_extracts/extract_care_home.R
  Production_scripts/Process_extracts/extract_cmh.R
  Production_scripts/Process_extracts/extract_district_nursing.R
  Production_scripts/Process_extracts/extract_home_care.R
  Production_scripts/Process_extracts/extract_maternity.R
  Production_scripts/Process_extracts/extract_mental_health.R
  Production_scripts/Process_extracts/extract_nrs_deaths.R
  Production_scripts/Process_extracts/extract_outpatients.R
  Production_scripts/Process_extracts/extract_prescribing.R
  Production_scripts/Social_Care/Home_Care.R
  Production_scripts/Social_Care/Social_Care_Lookups/lookup_sc_demographics.R
  Production_scripts/Social_Care/Social_Care_Lookups/lookup_social_care_client.R
Labels: SPSS to R

#365 Add smrtype variable to extracts
  NAMESPACE
  Production_scripts/Process_extracts/extract_a&e.R
  Production_scripts/Process_extracts/extract_acute_incl_gls.R
  Production_scripts/Process_extracts/extract_cmh.R
  Production_scripts/Process_extracts/extract_district_nursing.R
  Production_scripts/Process_extracts/extract_maternity.R
  Production_scripts/Process_extracts/extract_mental_health.R
  Production_scripts/Process_extracts/extract_nrs_deaths.R
  Production_scripts/Process_extracts/extract_outpatients.R
  Production_scripts/Process_extracts/extract_prescribing.R
  R/add_smr_type.R
  R/process_homelessness_extract.R
  man/add_smr_type.Rd
  tests/testthat/test-add_smr_type.R
Labels: SPSS to R, New Function

#353 Process Delayed Discharges extract
  Production_scripts/Process_extracts/extract_delayed_discharges.R
Labels: SPSS to R

#388 Convert homelessness extract script into a function
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_homelessness_tests.R
  Production_scripts/Process_extracts/extract_homelessness.R
  R/process_extract_homelessness.R
  R/process_tests_homelessness.R
  R/read_extract_homelessness.R
  man/process_extract_homelessness.Rd
  man/process_tests_homelessness.Rd
  man/read_extract_homelessness.Rd
Labels: SPSS to R

#392 Change `convert_eng_gp_prac...` to take and return a vector
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_mental_health_tests.R
  Production_scripts/Process_extracts/extract_mental_health.R
  R/convert_eng_gpprac_to_dummy.R
  R/createslf-package.R
  R/process_extract_mental_health.R
  R/process_tests_mental_health.R
  R/read_extract_mental_health.R
  man/convert_eng_gpprac_to_dummy.Rd
  man/process_extract_mental_health.Rd
  man/process_tests_mental_health.Rd
  man/read_extract_mental_health.Rd
  tests/testthat/test-convert_eng_gpprac_to_dummy.R
Labels: bug, enhancement

#389 Convert MH extract script into a function
  NAMESPACE
  R/process_extract_mental_health.R
  R/read_extract_mental_health.R
  man/process_extract_homelessness.Rd
  man/process_extract_mental_health.Rd
Labels: SPSS to R

#376 375 add year parameter
  R/write_tests_xlsx.R
  man/write_tests_xlsx.Rd
Labels: bug

#387 A new function to check if variables are in the data
  NAMESPACE
  R/check_variables_exist.R
  man/check_variables_exist.Rd
  tests/testthat/_snaps/check_variables_exist.md
  tests/testthat/test-check_variables_exist.R
Labels: New Function
