Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-02, with the labels that each got.

#136 #132 Deaths Extract Processing Conversion
  DEATHS_extract_processing.R
Labels: SPSS to R

#135 #88 LTC Extract Processing Conversion
  LTC_extracts_DRAFT.R
  R/convert_year_types.R
  tests/testthat/test-convert_year_types.R
Labels: SPSS to R

#141 Expand is missing
  R/is_missing.R
  tests/testthat/test-is_missing.R
Labels: enhancement, back-end

#148 Remove readr::read_csv and test functions
  R/read_lookups.R
Labels: bug, back-end

#143 Rename IT extracts (SPSS)
  2014-15/A01b Set up 1415 Macros.sps
  2015-16/A01b Set up 1516 Macros.sps
  2016-17/A01b Set up 1617 Macros.sps
  2017-18/A01b Set up 1718 Macros.sps
  2018-19/A01b Set up 1819 Macros.sps
  2019-20/A01b Set up 1920 Macros.sps
  2020-21/A01b Set up 2021 Macros.sps
  2021-22/A01b Set up 2122 Macros.sps
  All_years/01-Macros/Macro-01-Universal.sps
Labels: back-end, march-22 Update
