Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-10, with the labels that each got.

#377 331 ppa in c01
  NAMESPACE
  R/add_ppa_flag.R
  man/add_ppa_flag.Rd
  tests/testthat/test-add_ppa_flag.R
Labels: SPSS to R, New Function

#420 Bug - CH name lookup
  NAMESPACE
  R/get_ch_name_lookup_path.R
  R/get_slf_lookup_paths.R
  man/get_ch_name_lookup_path.Rd
  man/get_sc_demog_lookup_path.Rd
Labels: bug

#401 Improve get file path messages
  R/get_file_paths.R
  man/get_slf_dir.Rd
  tests/testthat/test-get_file_paths.R
Labels: enhancement

#405 233 convert sds spss year specific
  NAMESPACE
  Production_scripts/Process_extracts/extract_sds.R
  R/get_sc_sds_episodes_path.R
  R/get_source_extract_path.R
  man/get_sc_sds_episodes_path.Rd
  man/get_source_extract_path.Rd
Labels: SPSS to R
