Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-06, with the labels that each got.

#246 Fix - duplicate rows being created in HC costs
  All_years/03-Costs/Costs-04-home_care.R
Labels: bug, June-2022 update, Priority: High

#247 Fix some build errors/warnings.
  R/get_existing_data_for_tests.R
  tests/testthat/test-get_practice_details_path.R
Labels: bug, PR: unreviewed

#234 #89 NRS Deaths Extract
  Production_scripts/Process_extracts/extract_nrs_deaths.R
Labels: SPSS to R, PR: unreviewed

#252 include permission fix
  R/write_tests_xlsx.R
Labels: enhancement, PR: unreviewed

#225 Make fst tweaks
  Make_R_files/make_fst_version_functions.R
  Make_R_files/make_fst_versions.R
  NEWS.md
Labels: enhancement, June-2022 update

#245 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Priority: Low

#265 Change postcode function name
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
Labels: SPSS to R, PR: unreviewed

#266 Amend tests function
  R/produce_source_extract_tests.R
  man/produce_source_extract_tests.Rd
Labels: SPSS to R, PR: unreviewed

#239 #177 A&E Extract Tests
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_ae_tests.R
  man/produce_source_extract_tests.Rd~refs/remotes/origin/main-R
Labels: SPSS to R, PR: unreviewed

#271 Add two functions for dealing with financial year intervals
  NAMESPACE
  R/get_fy_dates.R
  R/is_date_in_fyyear.R
  man/fy_interval.Rd
  man/is_date_in_year.Rd
  tests/testthat/test-get_fy_dates.R
  tests/testthat/test-is_date_in_fyyear.R
Labels: enhancement, SPSS to R, Priority: High, PR: unreviewed

#273 Updates to the GitHub actions
  .github/workflows/Check-code.yaml
  .github/workflows/document.yaml
  .github/workflows/lint.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/pr-triage-dummy.yml
  .github/workflows/pr-triage.yml
  .github/workflows/style.yaml
Labels: PR: unreviewed
