Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-03, with the labels that each got.

#155 Update test to include counts of beddays per Health Board
  2014-15/B01X Acute_tests.sps
  2014-15/B02X Maternity_tests.sps
  2014-15/B03X Outpatient_tests.sps
  2014-15/B04X MentalHealth_tests.sps
  2014-15/B05X A&E_tests.sps
  2015-16/B01X Acute_tests.sps
  2015-16/B02X Maternity_tests.sps
  2015-16/B03X Outpatient_tests.sps
  2015-16/B04X MentalHealth_tests.sps
  2015-16/B05X A&E_tests.sps
  2016-17/B01X Acute_tests.sps
  2016-17/B02X Maternity_tests.sps
  2016-17/B03X Outpatient_tests.sps
  2016-17/B04X MentalHealth_tests.sps
  2016-17/B05X A&E_tests.sps
  2017-18/B01X Acute_tests.sps
  2017-18/B02X Maternity_tests.sps
  2017-18/B03X Outpatient_tests.sps
  2017-18/B04X MentalHealth_tests.sps
  2017-18/B05X A&E_tests.sps
  2018-19/B01X Acute_tests.sps
  2018-19/B02X Maternity_tests.sps
  2018-19/B03X Outpatient_tests.sps
  2018-19/B04X MentalHealth_tests.sps
  2018-19/B05X A&E_tests.sps
  2019-20/B01X Acute_tests.sps
  2019-20/B02X Maternity_tests.sps
  2019-20/B03X Outpatient_tests.sps
  2019-20/B04X MentalHealth_tests.sps
  2019-20/B05X A&E_tests.sps
  2020-21/B01X Acute_tests.sps
  2020-21/B02X Maternity_tests.sps
  2020-21/B03X Outpatient_tests.sps
  2020-21/B04X MentalHealth_tests.sps
  2020-21/B05X A&E_tests.sps
  2021-22/B01X Acute_tests.sps
  2021-22/B02X Maternity_tests.sps
  2021-22/B03X Outpatient_tests.sps
  2021-22/B04X MentalHealth_tests.sps
  2021-22/B05X A&E_tests.sps
Labels: Testing, march-22 Update

#149 #77 Convert Postcode lookup
  All_years/01-Macros/Macro-01-Universal.sps
  NAMESPACE
  Production_scripts/Lookup-01-Postcode.R
  R/convert_ca_to_lca.R
  R/get_fy_dates.R
  man/ca_to_lca.Rd
  tests/testthat/test-convert_ca_to_lca.R
Labels: SPSS to R

#150 #79 Convert GP Lookup
  DEATHS_extract_processing.R
  LTC_extracts_DRAFT.R
  Production_scripts/Lookup-02-GP_practice.R
  R/read_lookups.R
  convert_gp_lookup.R
Labels: SPSS to R

#140 # 84 Convert sc demographics
  NAMESPACE
  Production_scripts/B12_Create_CHI-LTC_Lookup.R
  Production_scripts/Lookup-04-Create-CHI-Deceased.R
  Production_scripts/Lookup-05-Social_Care_Demographics.R
  R/get_connection_PHS_database.R
  man/phs_db_connection.Rd
  man/read_gpprac_file.Rd
Labels: SPSS to R

#165 Rename Extract function
  NAMESPACE
  R/get_boxi_extract_path.R
  R/get_source_extract_path.R
  man/extract_path.Rd
  man/get_boxi_extract_path.Rd
  man/get_source_extract_path.Rd
Labels: back-end

#167 Rename file and fn - gp prac code to dummy
  NAMESPACE
  R/convert_eng_gpprac_to_dummy.R
  man/convert_eng_gpprac_to_dummy.Rd
  tests/testthat/test-convert_eng_gpprac_to_dummy.R
  tests/testthat/test-eng_gp_to_dummy.R
Labels: back-end

#168 Rename Files
  R/00-update_refs.R
  R/check_char_is_missing.R
  R/set_utils-pipe.R
  man/dd_period.Rd
  man/is_missing.Rd
  man/it_extract_ref.Rd
  man/latest_update.Rd
  man/pipe.Rd
  man/previous_update.Rd
  tests/testthat/test-00-update_refs.R
  tests/testthat/test-check_char_is_missing.R
Labels: back-end

#166 Source Extract fn
  R/get_boxi_extract_path.R
  R/get_source_extract_path.R
  man/get_boxi_extract_path.Rd
  man/get_source_extract_path.Rd
Labels: back-end

#156 Amend test scripts
  Production_scripts/Lookup-01b-Postcode-tests.R
  Production_scripts/Lookup-02b-GP-practice-tests.R
  Production_scripts/Lookup-04-Create-CHI-Deceased-tests.R
  Production_scripts/Lookup-05-Social_Care_Demographics-tests.R
  Production_scripts/Social_Care-01_ch_episodes_tests.R
  R/produce_slf_gpprac_tests.R
  R/produce_slf_postcode_tests.R
  R/write_tests_xlsx.R
Labels: Testing
