Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-11, with the labels that each got.

#419 Changes due to `tidyselect` 1.2.0
  DESCRIPTION
  R/add_nsu_cohort.R
  R/add_ppa_flag.R
  R/create_monthly_beddays.R
  R/fix_duplicates.R
  R/get_existing_data_for_tests.R
  R/process_extract_acute.R
  R/process_extract_ae.R
  R/process_extract_cmh.R
  R/process_extract_homelessness.R
  R/process_extract_maternity.R
  R/process_extract_mental_health.R
  R/process_extract_outpatients.R
  R/process_lookup_sc_client.R
  R/process_lookup_sc_demographics.R
  R/produce_sc_ch_episodes_tests.R
  R/produce_sc_demog_lookup_tests.R
  R/produce_slf_deaths_tests.R
  R/produce_slf_gpprac_tests.R
  R/produce_slf_homelessness_tests.R
  R/produce_slf_postcode_tests.R
  R/produce_source_ch_tests.R
  R/produce_source_cmh_tests.R
  R/produce_source_extract_tests.R
  R/produce_source_hc_tests.R
  R/produce_source_nrs_tests.R
  R/produce_source_pis_tests.R
  R/read_lookup_sc_client.R
  R/read_lookup_sc_demographics.R
Labels: Testing

#407 378 alarms + telecare year specific tests
  All_years/03-Costs/Costs-04-home_care.R
  All_years/04-Social_Care/00-Social_Care_functions.R
  All_years/04-Social_Care/02-Home_care_data.R
  All_years/04-Social_Care/04-SDS_data.R
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_alarms_telecare_tests.R
  R/produce_source_at_tests.R
  man/produce_sc_ch_episodes_tests.Rd
  man/produce_sc_demog_lookup_tests.Rd
  man/produce_source_at_tests.Rd
Labels: Testing

#427 Convert care home costs lookup into a function for processing in phase 1b
  R/process_costs_ch_rmd.R
  Rmarkdown/ch_costs.Rmd
  man/process_costs_ch_rmd.Rd
Labels: SPSS to R

#428 Convert home care costs lookup into a function for processing in phase 1b
  R/process_costs_hc_rmd.R
  Rmarkdown/hc_costs.Rmd
  man/process_costs_hc_rmd.Rd
Labels: SPSS to R

#436 Fixes for GPOOH smrtype
  2014-15/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2015-16/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2016-17/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2017-18/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2018-19/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2019-20/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2020-21/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2021-22/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2022-23/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
Labels: December-2022-update

#439 Fix sds option4 bug - SPSS (December 2022 Update)
  All_years/04-Social_Care/00-Social_Care_functions.R
  All_years/04-Social_Care/04-SDS_data.R
Labels: bug

#429 BUG - Fix sc client function
  All_years/04-Social_Care/04-SDS_data.R
  DESCRIPTION
  R/read_lookup_sc_client.R
  man/read_lookup_sc_client.Rd
Labels: bug, Priority: High

#449 New functions for `fix_sc_dates`
  NAMESPACE
  R/fix_sc_dates.R
  man/fix_sc_end_dates.Rd
  man/fix_sc_start_dates.Rd
  tests/testthat/test-fix_sc_dates.R
Labels: New Function

#452 Make client variable as an integer
  R/process_extract_home_care.R
  R/process_lookup_sc_client.R
  R/process_sc_all_home_care.R
  R/read_lookup_sc_client.R
Labels: bug

#458 Update references for training branch
  R/00-update_refs.R
Labels: Training

#445 Changes to the PIS data
  2014-15/B06 Process PIS extract.sps
  2014-15/B06X PIS_tests.sps
  2014-15/C10 Final tidy for Episode file.sps
  2014-15/D01 Make Individual File.sps
  2014-15/D05 Final tidy for Individual file.sps
  2014-15/D05X Individual file tests.sps
  2015-16/B06 Process PIS extract.sps
  2015-16/B06X PIS_tests.sps
  2015-16/C10 Final tidy for Episode file.sps
  2015-16/D01 Make Individual File.sps
  2015-16/D05 Final tidy for Individual file.sps
  2015-16/D05X Individual file tests.sps
  2016-17/B06 Process PIS extract.sps
  2016-17/B06X PIS_tests.sps
  2016-17/C10 Final tidy for Episode file.sps
  2016-17/D01 Make Individual File.sps
  2016-17/D05 Final tidy for Individual file.sps
  2016-17/D05X Individual file tests.sps
  2017-18/B06 Process PIS extract.sps
  2017-18/B06X PIS_tests.sps
  2017-18/C10 Final tidy for Episode file.sps
  2017-18/D01 Make Individual File.sps
  2017-18/D05 Final tidy for Individual file.sps
  2017-18/D05X Individual file tests.sps
  2018-19/B06 Process PIS extract.sps
  2018-19/B06X PIS_tests.sps
  2018-19/C10 Final tidy for Episode file.sps
  2018-19/D01 Make Individual File.sps
  2018-19/D05 Final tidy for Individual file.sps
  2018-19/D05X Individual file tests.sps
  2019-20/B06 Process PIS extract.sps
  2019-20/B06X PIS_tests.sps
  2019-20/C10 Final tidy for Episode file.sps
  2019-20/D01 Make Individual File.sps
  2019-20/D05 Final tidy for Individual file.sps
  2019-20/D05X Individual file tests.sps
  2020-21/B06 Process PIS extract.sps
  2020-21/B06X PIS_tests.sps
  2020-21/C10 Final tidy for Episode file.sps
  2020-21/D01 Make Individual File.sps
  2020-21/D05 Final tidy for Individual file.sps
  2020-21/D05X Individual file tests.sps
  2021-22/B06 Process PIS extract.sps
  2021-22/B06X PIS_tests.sps
  2021-22/C10 Final tidy for Episode file.sps
  2021-22/D01 Make Individual File.sps
  2021-22/D05 Final tidy for Individual file.sps
  2021-22/D05X Individual file tests.sps
  2022-23/B06 Process PIS extract.sps
  2022-23/B06X PIS_tests.sps
  2022-23/C10 Final tidy for Episode file.sps
  2022-23/D01 Make Individual File.sps
  2022-23/D05 Final tidy for Individual file.sps
  2022-23/D05X Individual file tests.sps
  NEWS.md
Labels: December-2022-update

#454 Remove code which changes dates to numeric
  R/process_extract_mental_health.R
Labels: bug

#463 Fix homelessness filtering when we don't have completeness data
  R/process_extract_homelessness.R
Labels: bug, Priority: High, December-2022-update
