Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-12, with the labels that each got.

#446 318 add tests for the lookup file path functions
  R/get_lookup_paths.R
  man/get_datazone_pop_path.Rd
  man/get_gpprac_ref_path.Rd
  man/get_locality_path.Rd
  man/get_simd_path.Rd
  man/get_spd_path.Rd
  tests/testthat/test-get_lookup_paths.R
Labels: documentation, Testing, Priority: Low

#464 Rename demographic cohort functions
  R/create_demographic_lookup.R
  man/assign_adult_major_cohort.Rd
  man/assign_child_major_cohort.Rd
  man/assign_comm_living_cohort.Rd
  man/assign_demographic_cohorts.Rd
  man/assign_eol_cohort.Rd
  man/assign_frailty_cohort.Rd
  man/assign_high_cc_cohort.Rd
  man/assign_low_cc_cohort.Rd
  man/assign_maternity_cohort.Rd
  man/assign_medium_cc_cohort.Rd
  man/assign_mh_cohort.Rd
  man/assign_substance_cohort.Rd
  man/create_demographic_cohorts.Rd
  tests/testthat/test-create_demographic_lookup.R
Labels: enhancement

#462 Transform `anon_chi` from the episode file to `chi`
  All_years/04-Social_Care/00-Social_Care_functions.R
  DESCRIPTION
  NAMESPACE
  R/anon_chi.R
  R/get_existing_data_for_tests.R
  R/read_anon_chi_lookups.R
  man/convert_anon_chi_to_chi.Rd
  man/convert_chi_to_anon_chi.Rd
  man/read_anon_to_chi.Rd
  man/read_chi_to_anon.Rd
  tests/testthat/_snaps/anon_chi.md
  tests/testthat/test-anon_chi.R
  tests/testthat/test-get_existing_data_for_tests.R
Labels: bug, Priority: Low

#481 Rename ltc file
  R/get_ltcs_path.R
  R/process_sc_all_alarms_telecare.R
Labels: bug, Priority: Low

#486 Amend missing/extra variables
  R/process_extract_district_nursing.R
  R/process_extract_mental_health.R
Labels: bug, SPSS to R, Priority: Low, checking

#503 Convert Home Care tests into a function
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_home_care_tests.R
  R/process_tests_home_care.R
  R/write_tests_xlsx.R
  man/process_tests_home_care.Rd
Labels: Priority: Low, New Function

#496 Convert SC demographics tests into a function
  NAMESPACE
  Production_scripts/Social_Care/Social_Care_Lookups/Produce_social_care_lookup_tests/lookup_sc_demographics_tests.R
  R/process_tests_sc_demographics.R
  man/process_tests_sc_demographics.Rd
  man/write_tests_xlsx.Rd
Labels: SPSS to R, Priority: Low, New Function

#507 Convert all SC CH tests into a function
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_all_sc_ch_tests.R
  R/process_tests_sc_ch_episodes.R
  man/process_tests_sc_ch_episodes.Rd
Labels: Priority: Low, New Function

#505 Convert DN tests into a function for processing
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_district_nursing_tests.R
  R/process_tests_district_nursing.R
  man/process_tests_district_nursing.Rd
Labels: Priority: Low, New Function

#504 Convert SDS tests into a function for processing
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_sds_tests.R
  R/process_tests_sds.R
  R/produce_source_sds_tests.R
  man/process_tests_sds.Rd
Labels: Priority: Low, New Function

#497 Convert LTCs tests into a function for processing
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_chi_ltc_tests.R
  R/process_tests_ltcs.R
  man/process_tests_ltcs.Rd
Labels: Priority: Low, New Function

#441 Translation of C05
  NAMESPACE
  R/correct_demographics.R
  R/match_on_ltcs.R
  man/correct_demographics.Rd
  man/match_on_ltcs.Rd
Labels: SPSS to R, Priority: Low

#471 GP Out of Hours
  NAMESPACE
  Production_scripts/Process_extracts/extract_gp_ooh.R
  R/add_smr_type.R
  R/get_boxi_extract_path.R
  R/get_slf_lookup_paths.R
  man/add_smr_type.Rd
  man/get_boxi_extract_path.Rd
  man/get_dd_path.Rd
  man/get_file_path.Rd
  man/get_ltcs_path.Rd
  man/get_nsu_path.Rd
  man/get_practice_details_path.Rd
  man/get_readcode_lookup_path.Rd
  man/get_slf_ch_name_lookup_path.Rd
  tests/testthat/test-add_smr_type.R
  tests/testthat/test-get_fy_dates.R
Labels: SPSS to R, Priority: High

#484 Update PIS code to deal with new extract
  R/produce_source_pis_tests.R
  R/read_extract_prescribing.R
Labels: SPSS to R, December-2022-update

#510 Add new functions to get the path of the temp files
  NAMESPACE
  R/get_temp_file_paths.R
  man/get_slf_ep_temp_path.Rd
  man/get_slf_indiv_temp_path.Rd
  man/get_slf_temp_path.Rd
Labels: Priority: High, New Function
