Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-07, with the labels that each got.

#279 Tests bug
  R/calculate_measures.R
Labels: bug, SPSS to R

#280 Remove typo
  NAMESPACE
  R/create_person_id.R
Labels: bug

#289 Fix write tests function
  R/write_tests_xlsx.R
  man/write_tests_xlsx.Rd
Labels: bug, Priority: High

#290 Fix some bugs in the main home care code
  Production_scripts/Social_Care/Home_Care.R
Labels: bug, Priority: High

#293 Bug fix - cost variables should be '_cost' not '_costs'
  R/create_monthly_costs.R
Labels: bug, Priority: High

#282 Update test scripts - bug
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_ae_tests.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_all_sc_ch_tests.R
  R/produce_test_comparison.R
Labels: bug

#249 #211 Year Specific Source Home Care R
  Production_scripts/Create_social_care_lookups/lookup_social_care_client.R
  Production_scripts/Process_extracts/extract_home_care.R
  R/create_person_id.R
  R/get_ch_name_lookup_path.R
  _pkgdown.yml
  man/create_person_id.Rd
Labels: SPSS to R, PR: unreviewed

#298 Adding an action to do R CMD Check on GitHub
  .Rbuildignore
  .github/workflows/R-CMD-check.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  R/find_latest_file.R
  README.md
  codecov.yml
  man/find_latest_file.Rd
  tests/testthat/test-check_char_is_missing.R
  tests/testthat/test-check_year_format.R
  tests/testthat/test-create_monthly_beddays.R
  tests/testthat/test-get_cohorts_paths.R
  tests/testthat/test-get_costs_paths.R
  tests/testthat/test-get_dd_path.R
  tests/testthat/test-get_existing_data_for_tests.R
  tests/testthat/test-get_file_paths.R
  tests/testthat/test-get_it_extract_paths.R
  tests/testthat/test-get_nsu_paths.R
  tests/testthat/test-get_practice_details_path.R
  tests/testthat/test-get_sc_ch_episodes_path.R
  tests/testthat/test-get_sc_demog_path.R
  tests/testthat/test-get_slf_lookup_paths.R
  tests/testthat/test-get_sparra_hhg_paths.R
Labels: enhancement, Testing, Priority: Low

#297 Format tests
  DESCRIPTION
  R/write_tests_xlsx.R
Labels: Testing

#292 Bug/ch costs
  Production_scripts/Create_costs/costs-care_home.R
Labels: bug, Priority: High

#286 Check scripts
  Production_scripts/Create_slf_lookups/lookup_ltc.R
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
  Production_scripts/Process_extracts/extract_a&e.R
  Production_scripts/Process_extracts/extract_cmh.R
  Production_scripts/Process_extracts/extract_district_nursing.R
  Production_scripts/Process_extracts/extract_mental_health.R
  Production_scripts/Process_extracts/extract_nrs_deaths.R
Labels: bug

#281 Outpatients tests
  Production_scripts/Process_extracts/Produce_extract_tests/extract_outpatients_tests.R
Labels: Testing
