Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-08, with the labels that each got.

#287 PIS extract tests
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_prescribing_tests.R
  Production_scripts/Process_extracts/extract_prescribing.R
  R/produce_source_pis_tests.R
  man/produce_source_pis_tests.Rd
Labels: Testing, SPSS to R

#296 Test scripts cleanup
  Production_scripts/Process_extracts/Produce_extract_tests/extract_acute_incl_gls_tests.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_ae_tests.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_all_sc_ch_tests.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_maternity_tests.R
  Production_scripts/Process_extracts/Produce_extract_tests/extract_mental_health_tests.R
  R/produce_test_comparison.R
  tests/testthat/test-produce_test_comparison.R
Labels: Testing

#316 Fix permissions on `write_*` functions
  R/write_data.R
Labels: bug, Priority: High

#306 NRS tests
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_nrs_tests.R
  R/produce_source_nrs_tests.R
  man/calculate_measures.Rd
  man/produce_source_extract_tests.Rd
  man/produce_source_nrs_tests.Rd
Labels: Testing

#305 Expand is date in year
  NAMESPACE
  Production_scripts/Process_extracts/extract_home_care.R
  R/is_date_in_fyyear.R
  man/compute_mid_year_age.Rd
  man/convert_date_to_numeric.Rd
  man/convert_numeric_to_date.Rd
  man/end_fy.Rd
  man/fy_interval.Rd
  man/is_date_in_fyyear.Rd
  man/is_date_in_year.Rd
  man/midpoint_fy.Rd
  man/start_fy.Rd
  tests/testthat/test-is_date_in_fyyear.R
Labels: enhancement, SPSS to R, Priority: High

#310 308 update create monthly beddays
  R/create_monthly_beddays.R
  tests/testthat/_snaps/create_monthly_beddays.md
  tests/testthat/test-create_monthly_beddays.R
Labels: enhancement

#294 Update convert_year_to_fyyear to handle vectors of years
  R/check_year_format.R
  R/convert_year_types.R
  tests/testthat/test-check_year_format.R
  tests/testthat/test-convert_fyyear_to_year.R
  tests/testthat/test-convert_year_to_fyyear.R
  tests/testthat/test-convert_year_types.R
  tests/testthat/test-is_date_in_fyyear.R
Labels: bug, enhancement

#327 Removed documentation for parameter that no longer exists
  R/produce_source_nrs_tests.R
  man/produce_source_nrs_tests.Rd
Labels: bug

#312 307 create stay function
  NAMESPACE
  Production_scripts/Process_extracts/extract_acute_incl_gls.R
  Production_scripts/Process_extracts/extract_maternity.R
  Production_scripts/Process_extracts/extract_mental_health.R
  R/calculate_stay.R
  R/produce_slf_homelessness_tests.R
  man/calculate_stay.Rd
  man/compute_mid_year_age.Rd
  man/convert_date_to_numeric.Rd
  man/convert_numeric_to_date.Rd
  man/end_fy.Rd
  man/fy_interval.Rd
  man/is_date_in_fyyear.Rd
  man/midpoint_fy.Rd
  man/produce_slf_homelessness_tests.Rd
  man/start_fy.Rd
  tests/testthat/_snaps/calculate_stay.md
  tests/testthat/test-calculate_stay.R
Labels: enhancement, Priority: High, New Function

#323 LTC IT extract tests
  DESCRIPTION
  Production_scripts/Process_extracts/Produce_extract_tests/extract_chi_ltc_tests.R
  Production_scripts/Process_extracts/extract_mental_health.R
Labels: Testing, SPSS to R

#352 Bug calculate stay
  R/calculate_stay.R
  tests/testthat/_snaps/calculate_stay.md
  tests/testthat/test-calculate_stay.R
  tests/testthat/test-get_sc_ch_episodes_path.R
  tests/testthat/test-get_slf_lookup_paths.R
Labels: bug

#223 Year Specific Source CH Extract
  Production_scripts/Create_social_care_lookups/Produce_social_care_lookup_tests/lookup_sc_demographics_tests.R
  Production_scripts/Create_social_care_lookups/lookup_care_home_name.R
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
  Production_scripts/Create_social_care_lookups/lookup_social_care_client.R
  Production_scripts/Process_extracts/extract_care_home.R
  Production_scripts/Social_Care/Social_Care_Lookups/Produce_social_care_lookup_tests/lookup_sc_demographics_tests.R
  Production_scripts/Social_Care/Social_Care_Lookups/lookup_social_care_client.R
  R/get_fy_dates.R
  man/produce_source_extract_tests.Rd~refs/remotes/origin/main-R
Labels: SPSS to R

#349 Remove the duplicate GP cluster script
  NAMESPACE
  Production_scripts/Create_slf_lookups/lookup_gp_cluster.R
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
  R/get_slf_lookup_paths.R
  man/get_slf_ch_name_lookup_path.Rd
  man/get_slf_deaths_path.Rd
  man/get_slf_gp_cluster_path.Rd
  man/get_slf_gpprac_path.Rd
  man/get_slf_postcode_path.Rd
Labels: bug, Priority: Low

#356 GPPrac lookup bug
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
Labels: bug

#324 SC SDS data
  2021-22/B18 Process SOURCE SDS.sps
  All_years/04-Social_Care/04-SDS_data.R
Labels: Priority: High, September-2022 update

#361 359 change care home type of admission variable
  All_years/04-Social_Care/01-Care_home_data.sps
  NEWS.md
Labels: enhancement, Priority: High, September-2022 update

#358 302 updates and changes to gp out of hours
  2015-16/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2015-16/C10 Final tidy for Episode file.sps
  2015-16/D01 Make Individual File.sps
  2016-17/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2016-17/C10 Final tidy for Episode file.sps
  2016-17/D01 Make Individual File.sps
  2017-18/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2017-18/C10 Final tidy for Episode file.sps
  2017-18/D01 Make Individual File.sps
  2018-19/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2018-19/C10 Final tidy for Episode file.sps
  2018-19/D01 Make Individual File.sps
  2019-20/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2019-20/C10 Final tidy for Episode file.sps
  2019-20/D01 Make Individual File.sps
  2020-21/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2020-21/C10 Final tidy for Episode file.sps
  2020-21/D01 Make Individual File.sps
  2021-22/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2021-22/C10 Final tidy for Episode file.sps
  2021-22/D01 Make Individual File.sps
  2022-23/B09c Process GP Out of hours Contacts extract and link to Outcomes and Diagnoses.sps
  2022-23/C10 Final tidy for Episode file.sps
  2022-23/D01 Make Individual File.sps
  NEWS.md
Labels: September-2022 update

#348 Fix write out code
  Production_scripts/Create_slf_lookups/lookup_ltc.R
  Production_scripts/Process_extracts/extract_district_nursing.R
Labels: bug

#347 Remove usage of "zsav"/"sav" files
  All_years/04-Social_Care/02-Home_care_data.R
  Production_scripts/Create_costs/costs-gp_out_of_hours.R
  Production_scripts/Create_costs/costs_district_nursing.R
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_chi_deaths_tests.R
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_gp_practice_tests.R
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_postcode_tests.R
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
  Production_scripts/Process_extracts/extract_district_nursing.R
Labels: bug

#362 Update 2021/22 sparra and HHG
  2021-22/C08 Match on CHI variables - Cohorts SPARRA and HHG.sps
Labels: Priority: High, September-2022 update

#364 Sep22 remove sc
  2022-23/A05 Prepare Social Care Client lookup.sps
  2022-23/B16 Process SOURCE Home Care.sps
  2022-23/B16X Home Care tests.sps
  2022-23/B17 Process SOURCE Alarms Telecare.sps
  2022-23/B17X Alarms Telecare tests.sps
  2022-23/B18 Process SOURCE SDS.sps
  2022-23/B18X SDS tests.sps
  2022-23/C01 Make Episode File.sps
Labels: Priority: High, September-2022 update

#366 Update the cost uplift macro
  All_years/01-Macros/Macro-01-Universal.sps
Labels: enhancement, Priority: High, September-2022 update

#369 Remove the variable `sds_option` as it is recoded into `smrtype`
  2014-15/C01 Make Episode File.sps
  2014-15/C10 Final tidy for Episode file.sps
  2015-16/C01 Make Episode File.sps
  2015-16/C10 Final tidy for Episode file.sps
  2016-17/C01 Make Episode File.sps
  2016-17/C10 Final tidy for Episode file.sps
  2017-18/B18 Process SOURCE SDS.sps
  2017-18/B18X SDS tests.sps
  2017-18/C10 Final tidy for Episode file.sps
  2018-19/B18 Process SOURCE SDS.sps
  2018-19/B18X SDS tests.sps
  2018-19/C10 Final tidy for Episode file.sps
  2019-20/B18 Process SOURCE SDS.sps
  2019-20/B18X SDS tests.sps
  2019-20/C10 Final tidy for Episode file.sps
  2020-21/B18 Process SOURCE SDS.sps
  2020-21/B18X SDS tests.sps
  2020-21/C10 Final tidy for Episode file.sps
  2021-22/B18 Process SOURCE SDS.sps
  2021-22/B18X SDS tests.sps
  2021-22/C10 Final tidy for Episode file.sps
  2022-23/C10 Final tidy for Episode file.sps
  All_years/04-Social_Care/04-SDS_data.R
Labels: bug, September-2022 update

#372 Update SC send lca codes and names
  R/convert_sending_location_to_lca.R
Labels: bug, SPSS to R
