Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2022-05, with the labels that each got.

#158 #82 Costs-02-district_nursing
  DESCRIPTION
  NAMESPACE
  Production_scripts/Create_costs/costs_district_nursing.R
  R/check_year_format.R
  R/convert_codes_to_name.R
  man/hb_to_hbnames.Rd
  man/hscp_to_hscpnames.Rd
  tests/testthat/test-check_year_format.R
  tests/testthat/test-convert_codes_to_names.R
  tests/testthat/test-convert_year_types.R
Labels: SPSS to R

#203 Amend sc scripts
  2017-18/A05 Prepare Social Care Client lookup.sps
  2018-19/A05 Prepare Social Care Client lookup.sps
  2019-20/A05 Prepare Social Care Client lookup.sps
  2020-21/A05 Prepare Social Care Client lookup.sps
  2021-22/A05 Prepare Social Care Client lookup.sps
  All_years/01-Macros/Macro-01-Universal.sps
  All_years/02-Lookups/Lookup-05-Social_Care_Demographics.sps
  All_years/04-Social_Care/01-Care_home_data.sps
  All_years/04-Social_Care/02-Home_care_data.R
Labels: back-end, june-22-update

#195 Development SOP
  R_development_SOP.md
Labels: documentation, SPSS to R

#160 #95 A&E Extract Processing
  Production_scripts/Process_extracts/extract_a&e.R
  R/get_boxi_extract_path.R
  man/get_boxi_extract_path.Rd
Labels: SPSS to R

#196 #93 Convert District Nursing Extract
  Production_scripts/Process_extracts/extract_district_nursing.R
Labels: SPSS to R

#226 Replace Homelessness SPSS code with an error
  2016-17/B15 Process Homelessness extract.sps
  2017-18/B15 Process Homelessness extract.sps
  2018-19/B15 Process Homelessness extract.sps
  2019-20/B15 Process Homelessness extract.sps
  2020-21/B15 Process Homelessness extract.sps
  2021-22/B15 Process Homelessness extract.sps
  NEWS.md
Labels: bug, June-2022 update, Priority: High

#217 Add home care costs
  2014-15/C01 Make Episode File.sps
  2014-15/C10 Final tidy for Episode file.sps
  2014-15/D01 Make Individual File.sps
  2014-15/D05 Final tidy for Individual file.sps
  2015-16/C01 Make Episode File.sps
  2015-16/C10 Final tidy for Episode file.sps
  2015-16/D01 Make Individual File.sps
  2015-16/D05 Final tidy for Individual file.sps
  2016-17/C01 Make Episode File.sps
  2016-17/C10 Final tidy for Episode file.sps
  2016-17/D01 Make Individual File.sps
  2016-17/D05 Final tidy for Individual file.sps
  2017-18/B16 Process SOURCE Home Care.sps
  2017-18/C10 Final tidy for Episode file.sps
  2017-18/D01 Make Individual File.sps
  2017-18/D05 Final tidy for Individual file.sps
  2018-19/B16 Process SOURCE Home Care.sps
  2018-19/C10 Final tidy for Episode file.sps
  2018-19/D01 Make Individual File.sps
  2018-19/D05 Final tidy for Individual file.sps
  2019-20/B16 Process SOURCE Home Care.sps
  2019-20/C10 Final tidy for Episode file.sps
  2019-20/D01 Make Individual File.sps
  2019-20/D05 Final tidy for Individual file.sps
  2020-21/B16 Process SOURCE Home Care.sps
  2020-21/C10 Final tidy for Episode file.sps
  2020-21/D01 Make Individual File.sps
  2020-21/D05 Final tidy for Individual file.sps
  2021-22/B16 Process SOURCE Home Care.sps
  2021-22/C10 Final tidy for Episode file.sps
  2021-22/D01 Make Individual File.sps
  2021-22/D05 Final tidy for Individual file.sps
  All_years/03-Costs/Costs-04-home_care.R
  All_years/04-Social_Care/02-Home_care_data.R
Labels: June-2022 update, Priority: High

#222 Fix some typos in Care Home syntax
  All_years/03-Costs/Costs-01-care_home.sps
Labels: enhancement, June-2022 update

#230 BUG - Fix overcounting of preventable beddays
  2014-15/D01 Make Individual File.sps
  2015-16/D01 Make Individual File.sps
  2016-17/D01 Make Individual File.sps
  2017-18/D01 Make Individual File.sps
  2018-19/D01 Make Individual File.sps
  2019-20/D01 Make Individual File.sps
  2020-21/D01 Make Individual File.sps
  2021-22/D01 Make Individual File.sps
  NEWS.md
Labels: bug, June-2022 update

#224 Homelessness fixes
  Production_scripts/Process_extracts/extract_homelessness.R
  R/process_homelessness_extract.R
  man/process_homelessness_extract.Rd
Labels: bug, June-2022 update, Priority: High

#227 Make changes to GLS coding
  2014-15/B01 Process Acute (SMR01 and GLS) extract.sps
  2015-16/B01 Process Acute (SMR01 and GLS) extract.sps
  2016-17/B01 Process Acute (SMR01 and GLS) extract.sps
  2017-18/B01 Process Acute (SMR01 and GLS) extract.sps
  2018-19/B01 Process Acute (SMR01 and GLS) extract.sps
  2019-20/B01 Process Acute (SMR01 and GLS) extract.sps
  2020-21/B01 Process Acute (SMR01 and GLS) extract.sps
  2021-22/B01 Process Acute (SMR01 and GLS) extract.sps
  NEWS.md
Labels: June-2022 update, Priority: High

#235 Add more clusters to the GP practice lookup
  2014-15/C09 Match on postcode and gpprac variables.sps
  2014-15/D02 Match on postcode and gpprac variables.sps
  2015-16/C09 Match on postcode and gpprac variables.sps
  2015-16/D02 Match on postcode and gpprac variables.sps
  2016-17/C09 Match on postcode and gpprac variables.sps
  2016-17/D02 Match on postcode and gpprac variables.sps
  2017-18/C09 Match on postcode and gpprac variables.sps
  2017-18/D02 Match on postcode and gpprac variables.sps
  2018-19/C09 Match on postcode and gpprac variables.sps
  2018-19/D02 Match on postcode and gpprac variables.sps
  2019-20/C09 Match on postcode and gpprac variables.sps
  2019-20/D02 Match on postcode and gpprac variables.sps
  2020-21/C09 Match on postcode and gpprac variables.sps
  2020-21/D02 Match on postcode and gpprac variables.sps
  2021-22/C09 Match on postcode and gpprac variables.sps
  2021-22/D02 Match on postcode and gpprac variables.sps
  All_years/02-Lookups/00_get_gp_cluster_data.R
  All_years/02-Lookups/Lookup-02-GP_practice.sps
  All_years/02-Lookups/Lookup-02x-GP_practice_tests.sps
  NEWS.md
Labels: enhancement, June-2022 update, Priority: High

#240 Update `cij_ppa` logic to work with the numeric `cij_marker`
  2014-15/C01 Make Episode File.sps
  2015-16/C01 Make Episode File.sps
  2016-17/C01 Make Episode File.sps
  2017-18/C01 Make Episode File.sps
  2018-19/C01 Make Episode File.sps
  2019-20/C01 Make Episode File.sps
  2020-21/C01 Make Episode File.sps
  2021-22/C01 Make Episode File.sps
  NEWS.md
Labels: bug, June-2022 update

#241 Update monthly cost variables for all changed costs
  2018-19/B01a Fix C3 costs.sps
  2019-20/B01a Fix C3 costs.sps
  2020-21/B01a Fix C3 costs.sps
  2021-22/B01a Fix C3 costs.sps
  NEWS.md
Labels: bug, June-2022 update

#238 # 96 Mental Health Extract
  Production_scripts/Process_extracts/extract_mental_health.R
  R/get_boxi_extract_path.R
  R/get_source_extract_path.R
  man/get_boxi_extract_path.Rd
  man/get_source_extract_path.Rd
Labels: SPSS to R

#210 File permissions fix
  NAMESPACE
  Production_scripts/Create_costs/costs-care_home.R
  Production_scripts/Create_costs/costs-gp_out_of_hours.R
  Production_scripts/Create_costs/costs_district_nursing.R
  Production_scripts/Create_slf_lookups/lookup_chi_deaths.R
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
  Production_scripts/Create_slf_lookups/lookup_postcode.R
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
  Production_scripts/Create_social_care_lookups/lookup_social_care_client.R
  Production_scripts/Process_extracts/extract_a&e.R
  Production_scripts/Process_extracts/extract_acute_incl_gls.R
  Production_scripts/Process_extracts/extract_maternity.R
  Production_scripts/Process_extracts/extract_outpatients.R
  Production_scripts/Process_extracts/extract_prescribing.R
  R/get_file_paths.R
  R/process_homelessness_extract.R
  R/write_data.R
  inst/WORDLIST
  man/write_rds.Rd
  man/write_sav.Rd
  tests/testthat/test-write_data.R
Labels: bug, enhancement, SPSS to R

#236 #87 Community Mental Health Extract
  Production_scripts/Process_extracts/extract_cmh.R
Labels: SPSS to R

#214 Amend check mode
  Production_scripts/Create_costs/costs-care_home.R
  Production_scripts/Create_costs/costs-gp_out_of_hours.R
  Production_scripts/Create_costs/costs_district_nursing.R
  Production_scripts/Create_slf_lookups/lookup_chi_deaths.R
  Production_scripts/Create_slf_lookups/lookup_gp_practice.R
  Production_scripts/Create_slf_lookups/lookup_ltc.R
  Production_scripts/Create_slf_lookups/lookup_postcode.R
  Production_scripts/Create_social_care_lookups/lookup_sc_demographics.R
  Production_scripts/Create_social_care_lookups/lookup_social_care_client.R
  Production_scripts/Process_extracts/extract_acute_incl_gls.R
  Production_scripts/Process_extracts/extract_maternity.R
  Production_scripts/Process_extracts/extract_outpatients.R
  Production_scripts/Process_extracts/extract_prescribing.R
  R/get_cohorts_paths.R
  R/get_costs_paths.R
  R/get_dd_path.R
  R/get_nsu_paths.R
  R/get_practice_details_path.R
  R/get_sc_ch_episodes_path.R
  R/get_sc_demog_path.R
  R/get_slf_lookup_paths.R
  R/get_source_extract_path.R
  R/get_sparra_hhg_paths.R
  man/get_source_extract_path.Rd
  tests/testthat/test-get_cohorts_paths.R
  tests/testthat/test-get_costs_paths.R
  tests/testthat/test-get_dd_path.R
  tests/testthat/test-get_nsu_paths.R
  tests/testthat/test-get_practice_details_path.R
  tests/testthat/test-get_sc_ch_episodes_path.R
  tests/testthat/test-get_sc_demog_path.R
  tests/testthat/test-get_slf_lookup_paths.R
  tests/testthat/test-get_sparra_hhg_paths.R
Labels: SPSS to R, Priority: High

#242 Rename extract test function
  NAMESPACE
  Production_scripts/Process_extracts/Produce_extract_tests/extract_acute_incl_gls_tests.R
  R/produce_source_acute_tests.R
  man/produce_sc_ch_episodes_tests.Rd
  man/produce_sc_demog_lookup_tests.Rd
  man/produce_slf_deaths_tests.Rd
  man/produce_slf_gpprac_tests.Rd
  man/produce_slf_postcode_tests.Rd
  man/produce_source_extract_tests.Rd
  man/produce_test_comparison.Rd
Labels: enhancement

#244 #211 Index Functions
  NAMESPACE
  R/00-update_refs.R
  R/convert_codes_to_name.R
  R/convert_date_types.R
  R/get_dd_path.R
  R/process_homelessness_extract.R
  _pkgdown.yml
  man/convert_date_to_numeric.Rd
  man/convert_hb_to_hbnames.Rd
  man/convert_hscp_to_hscpnames.Rd
  man/convert_numeric_to_date.Rd
  man/get_dd_path.Rd
  man/get_dd_period.Rd
  tests/testthat/test-00-update_refs.R
  tests/testthat/test-convert_codes_to_names.R
  tests/testthat/test-convert_date_types.R
Labels: enhancement, PR: unreviewed
