Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-07, with the labels that each got.

#583 Add functions to automatically prepare the environment
  R/gzip_files.R
  R/make_lowercase_ext.R
  _targets.R
Labels: enhancement, Priority: Low, New Function

#717 Fix maternity beddays
  R/create_monthly_costs.R
  tests/testthat/test-create_monthly_costs.R
Labels: bug

#723 Changed to fix bug where beddays were all zero for delayed discharges
  R/link_delayed_discharge_eps.R
Labels: bug

#743 Fix some R CMD CHK build error and warnings
  .github/actions/spelling/expect.txt
  DESCRIPTION
  R/produce_test_comparison.R
  R/run_episode_file.R
  R/write_tests_xlsx.R
  man/join_cohort_lookups.Rd
Labels: Priority: High

#726 Write out as a partitioned arrow dataset
  R/run_episode_file.R
Labels: Priority: Low
