Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-09, with the labels that each got.

#823 BUG - Fix for the episode file tests
  R/get_existing_data_for_tests.R
  R/process_tests_episode_file.R
  man/read_file.Rd
Labels: bug, Priority: High, sept-update-23

#824 Update create_individual_file.R
  R/check_year_valid.R
  R/create_individual_file.R
  man/read_file.Rd
Labels: Priority: High

#825 Lizihao anu patch 1
  R/add_hri_variables.R
  R/create_individual_file.R
  man/add_hri_variables.Rd
Labels: Priority: High

#828 Add HL1 variables to individual file
  R/aggregate_by_chi.R
Labels: Priority: High, sept-update-23

#829 Fix aggregation_by_chi
  R/aggregate_by_chi.R
  R/create_individual_file.R
  man/aggregate_by_chi.Rd
  man/aggregate_by_chi_no_sc.Rd
Labels: Priority: High

#830 BUG - Fix episode file tests
  NAMESPACE
  R/get_existing_data_for_tests.R
  R/process_tests_episode_file.R
  man/get_existing_data_for_tests.Rd
Labels: bug, sept-update-23

#809 Add tests for `compute_mid_year_age`
  R/compute_mid_year_age.R
  man/read_file.Rd
  tests/testthat/test-compute_mid_year_age.R
Labels: Testing, Stale, Priority: Low

#800 Add a new function to set up keyring
  .github/actions/spelling/expect.txt
  NAMESPACE
  R/get_connection_PHS_database.R
  man/phs_db_connection.Rd
  man/setup_keyring.Rd
Labels: Stale, Priority: Low

#808 Add additional tests for `get_file_path`
  tests/testthat/test-get_file_paths.R
Labels: Testing, Stale, Priority: Low

#803 Rename `run_episode_file()` -> `create_episode_file()`
  NAMESPACE
  R/create_episode_file.R
  R/create_individual_file.R
  _targets.R
  man/add_acute_columns.Rd
  man/add_ae_columns.Rd
  man/add_all_columns.Rd
  man/add_at_columns.Rd
  man/add_ch_columns.Rd
  man/add_cij_columns.Rd
  man/add_cmh_columns.Rd
  man/add_dd_columns.Rd
  man/add_dn_columns.Rd
  man/add_gls_columns.Rd
  man/add_hc_columns.Rd
  man/add_hl1_columns.Rd
  man/add_ipdc_cols.Rd
  man/add_mat_columns.Rd
  man/add_mh_columns.Rd
  man/add_nrs_columns.Rd
  man/add_nsu_columns.Rd
  man/add_ooh_columns.Rd
  man/add_op_columns.Rd
  man/add_pis_columns.Rd
  man/add_sds_columns.Rd
  man/add_standard_cols.Rd
  man/aggregate_by_chi.Rd
  man/aggregate_ch_episodes.Rd
  man/clean_up_ch.Rd
  man/correct_cij_vars.Rd
  man/create_cohort_lookups.Rd
  man/create_cost_inc_dna.Rd
  man/create_episode_file.Rd
  man/create_individual_file.Rd
  man/fill_missing_cij_markers.Rd
  man/join_cohort_lookups.Rd
  man/load_ep_file_vars.Rd
  man/recode_gender.Rd
  man/remove_blank_chi.Rd
  man/store_ep_file_vars.Rd
Labels: documentation, Stale, Priority: Low

#798 Remove incorrect references to rds
  R/process_costs_rmd.R
  R/process_extract_acute.R
  R/process_extract_ae.R
  R/process_extract_alarms_telecare.R
  R/process_extract_care_home.R
  R/process_extract_cmh.R
  R/process_extract_consultations.R
  R/process_extract_delayed_discharges.R
  R/process_extract_district_nursing.R
  R/process_extract_gp_ooh.R
  R/process_extract_home_care.R
  R/process_extract_homelessness.R
  R/process_extract_maternity.R
  R/process_extract_mental_health.R
  R/process_extract_ooh_diagnosis.R
  R/process_extract_ooh_outcomes.R
  R/process_extract_outpatients.R
  R/process_extract_prescribing.R
  R/process_extract_sds.R
  R/process_lookup_ltc.R
  R/process_lookup_postcode.R
  R/process_lookup_sc_client.R
  R/process_lookup_sc_demographics.R
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_care_home.R
  R/process_sc_all_home_care.R
  R/process_sc_all_sds.R
  R/read_extract_gp_ooh.R
  man/process_costs_ch_rmd.Rd
  man/process_costs_dn_rmd.Rd
  man/process_costs_gp_ooh_rmd.Rd
  man/process_costs_hc_rmd.Rd
  man/process_extract_acute.Rd
  man/process_extract_ae.Rd
  man/process_extract_alarms_telecare.Rd
  man/process_extract_care_home.Rd
  man/process_extract_cmh.Rd
  man/process_extract_delayed_discharges.Rd
  man/process_extract_district_nursing.Rd
  man/process_extract_gp_ooh.Rd
  man/process_extract_home_care.Rd
  man/process_extract_homelessness.Rd
  man/process_extract_maternity.Rd
  man/process_extract_mental_health.Rd
  man/process_extract_ooh_consultations.Rd
  man/process_extract_ooh_diagnosis.Rd
  man/process_extract_ooh_outcomes.Rd
  man/process_extract_outpatients.Rd
  man/process_extract_prescribing.Rd
  man/process_extract_sds.Rd
  man/process_lookup_postcode.Rd
  man/process_lookup_sc_client.Rd
  man/process_lookup_sc_demographics.Rd
  man/process_sc_all_alarms_telecare.Rd
  man/process_sc_all_care_home.Rd
  man/process_sc_all_home_care.Rd
  man/process_sc_all_sds.Rd
  man/read_extract_gp_ooh.Rd
Labels: documentation, Stale, Priority: Low

#799 Make targets and tarchetypes required packages
  DESCRIPTION
Labels: Stale, Priority: Medium

#754 Update episode file functions to pass data through
  R/add_nsu_cohort.R
  R/create_episode_file.R
  R/fill_geographies.R
  R/get_source_extract_path.R
  R/get_sparra_hhg_paths.R
  R/join_deaths_data.R
  R/match_on_ltcs.R
  R/read_file.R
  _targets.R
  man/add_nsu_cohort.Rd
  man/create_episode_file.Rd
  man/create_individual_file.Rd
  man/fill_geographies.Rd
  man/join_cohort_lookups.Rd
  man/join_deaths_data.Rd
  man/match_on_ltcs.Rd
Labels: Priority: Low

#795 Update workflow to run against the development branch
  .github/workflows/lint-changed-files.yaml
  .github/workflows/test-coverage.yaml
Labels: Stale, Priority: Medium

#792 Remove package wide imports of `readr`
  NAMESPACE
  R/createslf-package.R
  R/process_extract_ae.R
  R/read_extract_acute.R
  R/read_extract_ae.R
  R/read_extract_cmh.R
  R/read_extract_district_nursing.R
  R/read_extract_homelessness.R
  R/read_extract_maternity.R
  R/read_extract_mental_health.R
  R/read_extract_nrs_deaths.R
  R/read_extract_outpatients.R
  R/read_extract_prescribing.R
  R/read_it_chi_deaths.R
  R/read_lookup_ltc.R
Labels: documentation, Priority: Low

#794 Handle OpenData extracts better
  NAMESPACE
  R/get_la_code_opendata_lookup.R
  R/process_extract_homelessness.R
  _targets.R
  man/get_la_code_opendata_lookup.Rd
  man/la_code_lookup.Rd
  man/process_extract_homelessness.Rd
  tests/testthat/_snaps/get_la_code_opendata_lookup.md
  tests/testthat/test-get_gpprac_opendata.R
  tests/testthat/test-get_la_code_opendata_lookup.R
Labels: Priority: Medium

#804 Fix the pkgdown site/job
  R/add_nsu_cohort.R
  R/add_ppa_flag.R
  R/aggregate_by_chi.R
  R/cost_uplift.R
  R/create_episode_file.R
  R/create_individual_file.R
  R/link_delayed_discharge_eps.R
  _pkgdown.yml
  man/add_acute_columns.Rd
  man/add_ae_columns.Rd
  man/add_all_columns.Rd
  man/add_at_columns.Rd
  man/add_ch_columns.Rd
  man/add_cij_columns.Rd
  man/add_cmh_columns.Rd
  man/add_dd_columns.Rd
  man/add_dn_columns.Rd
  man/add_gls_columns.Rd
  man/add_hc_columns.Rd
  man/add_hl1_columns.Rd
  man/add_ipdc_cols.Rd
  man/add_mat_columns.Rd
  man/add_mh_columns.Rd
  man/add_nrs_columns.Rd
  man/add_nsu_cohort.Rd
  man/add_nsu_columns.Rd
  man/add_ooh_columns.Rd
  man/add_op_columns.Rd
  man/add_pis_columns.Rd
  man/add_ppa_flag.Rd
  man/add_sds_columns.Rd
  man/add_standard_cols.Rd
  man/aggregate_by_chi.Rd
  man/aggregate_ch_episodes.Rd
  man/apply_cost_uplift.Rd
  man/clean_up_ch.Rd
  man/condition_cols.Rd
  man/correct_cij_vars.Rd
  man/create_cohort_lookups.Rd
  man/create_cost_inc_dna.Rd
  man/create_episode_file.Rd
  man/create_individual_file.Rd
  man/fill_missing_cij_markers.Rd
  man/join_cohort_lookups.Rd
  man/link_delayed_discharge_eps.Rd
  man/load_ep_file_vars.Rd
  man/lookup_uplift.Rd
  man/max_no_inf.Rd
  man/min_no_inf.Rd
  man/recode_gender.Rd
  man/remove_blank_chi.Rd
  man/store_ep_file_vars.Rd
Labels: documentation, Priority: Low

#787 Add new 'final' file path functions
  NAMESPACE
  R/create_episode_file.R
  R/create_individual_file.R
  R/get_final_file_paths.R
  man/get_slf_episode_path.Rd
  man/get_slf_individual_path.Rd
Labels: Priority: Medium

#793 Check scripts are in snake case
  R/create_individual_file.R
  R/get_boxi_extract_path.R
  R/get_source_extract_path.R
  R/link_delayed_discharge_eps.R
  R/process_extract_acute.R
  R/process_extract_ae.R
  R/process_extract_alarms_telecare.R
  R/process_extract_care_home.R
  R/process_extract_cmh.R
  R/process_extract_delayed_discharges.R
  R/process_extract_district_nursing.R
  R/process_extract_gp_ooh.R
  R/process_extract_home_care.R
  R/process_extract_maternity.R
  R/process_extract_mental_health.R
  R/process_extract_nrs_deaths.R
  R/process_extract_outpatients.R
  R/process_extract_prescribing.R
  R/process_extract_sds.R
  R/process_lookup_deaths.R
  R/process_lookup_sc_client.R
  R/read_extract_acute.R
  R/read_extract_ae.R
  R/read_extract_cmh.R
  R/read_extract_district_nursing.R
  R/read_extract_gp_ooh.R
  R/read_extract_homelessness.R
  R/read_extract_maternity.R
  R/read_extract_mental_health.R
  R/read_extract_nrs_deaths.R
  R/read_extract_ooh_consultations.R
  R/read_extract_ooh_diagnosis.R
  R/read_extract_ooh_outcomes.R
  R/read_extract_outpatients.R
  _targets.R
  man/get_boxi_extract_path.Rd
  man/get_source_extract_path.Rd
  man/join_sc_client.Rd
  man/link_delayed_discharge_eps.Rd
  man/process_slf_deaths_lookup.Rd
  man/read_extract_acute.Rd
  man/read_extract_ae.Rd
  man/read_extract_cmh.Rd
  man/read_extract_district_nursing.Rd
  man/read_extract_gp_ooh.Rd
  man/read_extract_homelessness.Rd
  man/read_extract_maternity.Rd
  man/read_extract_mental_health.Rd
  man/read_extract_nrs_deaths.Rd
  man/read_extract_ooh_consultations.Rd
  man/read_extract_ooh_diagnosis.Rd
  man/read_extract_ooh_outcomes.Rd
  man/read_extract_outpatients.Rd
Labels: Stale, Priority: Low

#817 Update the dev SOP
  .github/actions/spelling/expect.txt
  R_development_SOP.md
Labels: documentation, Stale, Priority: Low
