Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-02, with the labels that each got.

#442 C09 match Postcode and GP practice demographics
  .github/workflows/pkgdown.yaml
  NAMESPACE
  R/fill_geographies.R
  man/cascade_geographies.Rd
  man/fill_geographies.Rd
  man/recode_health_boards.Rd
  man/recode_hscp.Rd
  tests/testthat/test-match_pc_gpprac.R
Labels: SPSS to R, Priority: Low, Help required

#557 Add @export to missed documentation
  .github/actions/spelling/expect.txt
  NAMESPACE
  R/process_costs_rmd.R
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_home_care.R
  R/process_sc_all_sds.R
  R/read_sc_all_alarms_telecare.R
  R/read_sc_all_home_care.R
  R/read_sc_all_sds.R
  man/process_costs_ch_rmd.Rd
  man/process_costs_dn_rmd.Rd
  man/process_costs_gp_ooh_rmd.Rd
  man/process_costs_hc_rmd.Rd
Labels: bug

#544 Add `file_path` parameter to `read_XXX` functions
  .github/actions/spelling/expect.txt
  NAMESPACE
  R/get_gpprac_opendata.R
  R/process_lookup_gpprac.R
  R/process_lookup_postcode.R
  R/read_extract_gp_ooh.R
  R/read_extract_ooh_consultations.R
  R/read_extract_ooh_diagnosis.R
  R/read_extract_ooh_outcomes.R
  man/get_gpprac_opendata.Rd
  man/process_lookup_gpprac.Rd
  man/process_lookup_postcode.Rd
  man/read_extract_gp_ooh.Rd
  man/read_extract_ooh_consultations.Rd
  man/read_extract_ooh_diagnosis.Rd
  man/read_extract_ooh_outcomes.Rd
Labels: enhancement

#559 Ep file variable class fixes
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  R/add_nsu_cohort.R
  R/read_extract_acute.R
  R/read_extract_ae.R
  R/read_extract_cmh.R
  R/read_extract_district_nursing.R
  R/read_extract_mental_health.R
Labels: bug

#520 Care Home all episodes
  .github/actions/spelling/expect.txt
  DESCRIPTION
  NAMESPACE
  Production_scripts/Social_Care/care_home_all_episodes.R
  R/createslf-package.R
  R/fill_ch_names.R
  man/fill_ch_names.Rd
Labels: SPSS to R, Priority: High, Help required

#562 Tweaks to SC Client lookup
  R/process_lookup_sc_client.R
  R/read_lookup_sc_client.R
Labels: Priority: Low
