Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-01, with the labels that each got.

#533 Add `file_path` parameter to `read_XXX` functions
  R/read_extract_acute.R
  R/read_extract_ae.R
  R/read_extract_cmh.R
  R/read_extract_delayed_discharges.R
  R/read_extract_district_nursing.R
  R/read_extract_homelessness.R
  R/read_extract_maternity.R
  R/read_extract_mental_health.R
  R/read_extract_nrs_deaths.R
  R/read_extract_outpatients.R
  R/read_extract_prescribing.R
  R/read_lookup_chi_deaths.R
  R/read_lookup_ltc.R
  man/read_extract_acute.Rd
  man/read_extract_ae.Rd
  man/read_extract_cmh.Rd
  man/read_extract_delayed_discharges.Rd
  man/read_extract_district_nursing.Rd
  man/read_extract_homelessness.Rd
  man/read_extract_maternity.Rd
  man/read_extract_mental_health.Rd
  man/read_extract_nrs_deaths.Rd
  man/read_extract_outpatients.Rd
  man/read_extract_prescribing.Rd
  man/read_lookup_chi_deaths.Rd
  man/read_lookup_ltc.Rd
Labels: enhancement, Processing

#546 Update phs connection to use keyring
  .github/actions/spelling/expect.txt
  DESCRIPTION
  R/get_connection_PHS_database.R
Labels: enhancement

#547 Update `find_latest_file()`
  .github/actions/spelling/expect.txt
  R/find_latest_file.R
  man/find_latest_file.Rd
Labels: Priority: Low

#543 Amend extracts to return `null` when there is no year available
  NAMESPACE
  R/check_year_valid.R
  R/get_boxi_extract_path.R
  R/get_source_extract_path.R
  R/process_extract_cmh.R
  R/process_extract_delayed_discharges.R
  R/process_extract_district_nursing.R
  R/process_extract_homelessness.R
  R/read_extract_cmh.R
  R/read_extract_district_nursing.R
  R/read_extract_homelessness.R
  man/check_year_valid.Rd
  man/get_boxi_extract_path.Rd
  tests/testthat/test-check_year_valid.R
Labels: enhancement
