Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-03, with the labels that each got.

#564 Update test functions
  R/calculate_measures.R
  R/produce_test_comparison.R
  man/calculate_measures.Rd
  man/produce_test_comparison.Rd
Labels: Priority: High, checking

#560 Update social care parameters
  R/process_extract_alarms_telecare.R
  R/process_extract_care_home.R
  R/process_extract_home_care.R
  R/process_extract_sds.R
  R/process_lookup_sc_demographics.R
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_home_care.R
  R/process_sc_all_sds.R
  R/read_lookup_sc_demographics.R
  man/process_extract_alarms_telecare.Rd
  man/process_extract_care_home.Rd
  man/process_extract_home_care.Rd
  man/process_extract_sds.Rd
  man/process_lookup_sc_demographics.Rd
  man/process_sc_all_alarms_telecare.Rd
  man/process_sc_all_home_care.Rd
  man/process_sc_all_sds.Rd
  man/read_lookup_sc_demographics.Rd
Labels: enhancement, Processing

#588 Delete redundant scripts
  .Rbuildignore
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_chi_deaths_tests.R
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_gp_practice_tests.R
  Production_scripts/Create_slf_lookups/Produce_slf_lookup_tests/lookup_postcode_tests.R
  Production_scripts/Social_Care/Social_Care_Lookups/lookup_care_home_name.R
  Production_scripts/Social_Care/care_home_all_episodes.R
Labels: Priority: Low
