Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-10, with the labels that each got.

#841 Remove outdated comment
  R/get_source_extract_path.R
  _SPSS_archived/All_years/04-Social_Care/03-Alarms_Telecare_data.R
Labels: Priority: Low, small change

#840 Rename function `add_smrtype`
  R/add_smrtype.R
  R/process_extract_acute.R
  R/process_extract_ae.R
  R/process_extract_care_home.R
  R/process_extract_cmh.R
  R/process_extract_district_nursing.R
  R/process_extract_gp_ooh.R
  R/process_extract_homelessness.R
  R/process_extract_maternity.R
  R/process_extract_mental_health.R
  R/process_extract_nrs_deaths.R
  R/process_extract_outpatients.R
  R/process_extract_prescribing.R
  man/add_smrtype.Rd
Labels: enhancement, Priority: Medium

#837 00 sort bi extracts
  00_Sort_BI_Extracts.R
  R/create_episode_file.R
  copy_to_hscdiip.R
Labels: Priority: High, Dec-23-update
