Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-08, with the labels that each got.

#802 Fix locality
  R/process_lookup_postcode.R
Labels: bug, Priority: High

#767 Add simple scripts for running targets as a workbench job
  .Rbuildignore
  run_targets_1718.R
  run_targets_1819.R
  run_targets_1920.R
  run_targets_2021.R
  run_targets_2122.R
  run_targets_2223.R
Labels: sept-update-23

#791 786 duplicates of chi in individual files
  R/create_individual_file.R
  R/process_tests_individual_file.R
Labels: bug, Priority: High, sept-update-23

#797 fix warning on `:=`
  R/aggregate_by_chi.R
Labels: documentation

#811 Update news for September 23 update
  NEWS.md
Labels: Priority: Low, sept-update-23

#810 Fix issue with `case_match` types
  R/convert_sending_location_to_lca.R
  tests/testthat/_snaps/convert_sending_location_to_lca.md
  tests/testthat/test-convert_sending_location_to_lca.R
Labels: bug, Priority: High, sept-update-23

#816 Bug - Outpatients tests failing due to missing HSCP
  R/process_tests_outpatients.R
  R/produce_source_extract_tests.R
  man/produce_source_extract_tests.Rd
Labels: Priority: High, sept-update-23

#782 Add new function for counting records by sending location
  R/create_sending_location_test_flags.R
  man/create_demog_test_flags.Rd
  man/create_hb_cost_test_flags.Rd
  man/create_hb_test_flags.Rd
  man/create_hscp_test_flags.Rd
  man/create_lca_test_flags.Rd
  man/create_sending_location_test_flags.Rd
Labels: Priority: High, sept-update-23

#778 Create HRI Variables
  NAMESPACE
  R/add_hri_variables.R
  man/add_hri_variables.Rd
  man/flag_non_scottish_residents.Rd
  tests/testthat/test-flag_non_scottish_residents.R
Labels: enhancement, Priority: High, Help required, sept-update-23
