Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2023-04, with the labels that each got.

#613 C01 fix cij admtype
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  R/run_episode_file.R
Labels: bug

#616 Fix a bug in the SC Demographics
  .github/actions/spelling/expect.txt
  R/process_lookup_sc_demographics.R
Labels: bug, Priority: High

#614 Fix Care Home bugs
  .github/actions/spelling/expect.txt
  R/process_sc_all_care_home.R
Labels: bug, Priority: High

#615 Fix a Home Care bug
  .github/actions/spelling/expect.txt
  R/process_sc_all_home_care.R
Labels: bug, Priority: High

#618 Use integers for appropriate variables
  .github/actions/spelling/expect.txt
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_care_home.R
  R/process_sc_all_home_care.R
  R/process_sc_all_sds.R
  R/process_tests_sc_demographics.R
  R/read_lookup_sc_demographics.R
  R/read_sc_all_alarms_telecare.R
  R/read_sc_all_care_home.R
  R/read_sc_all_home_care.R
  R/read_sc_all_sds.R
Labels: enhancement, Priority: High

#599 Remove `{readxl}` dependency
  .github/actions/spelling/expect.txt
  DESCRIPTION
  R/fill_ch_names.R
  Rmarkdown/costs_district_nursing.Rmd
  Rmarkdown/costs_gp_ooh.Rmd
  Rmarkdown/costs_home_care.Rmd
Labels: Priority: Low

#597 Remove the dependency on `glue`
  R/add_ppa_flag.R
  R/convert_monthly_rows_to_vars.R
  R/create_demographic_lookup.R
  R/get_boxi_extract_path.R
  R/get_cohorts_paths.R
  R/get_connection_PHS_database.R
  R/get_costs_paths.R
  R/get_it_extract_paths.R
  R/get_lookup_paths.R
  R/get_ltcs_path.R
  R/get_nsu_paths.R
  R/get_practice_details_path.R
  R/get_sc_at_episodes_path.R
  R/get_sc_ch_episodes_path.R
  R/get_sc_demog_path.R
  R/get_sc_hc_episodes_path.R
  R/get_sc_sds_episodes_path.R
  R/get_slf_lookup_paths.R
  R/get_source_extract_path.R
  R/get_sparra_hhg_paths.R
  R/get_temp_file_paths.R
  R/is_missing.R
  R/process_costs_rmd.R
  R/process_extract_homelessness.R
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_sds.R
  R/produce_homelessness_completeness.R
  R/write_tests_xlsx.R
  tests/testthat/test-get_practice_details_path.R
Labels: Priority: Low

#587 Use internal function to capture English practices as a dummy code
  R/run_episode_file.R
Labels: enhancement, Priority: Low

#626 Update beddays test snapshot
  R/run_episode_file.R
  tests/testthat/_snaps/create_monthly_beddays.md
Labels: Testing, Priority: High

#627 Fix some variable names in acute
  R/process_extract_acute.R
  R/read_extract_acute.R
Labels: bug, Priority: High

#631 Fix a misnamed variable in `correct_demographics`
  .github/actions/spelling/expect.txt
  R/correct_demographics.R
  R/fill_geographies.R
Labels: bug

#629 Fix the case of the keytimex variables in CMH
  .github/actions/spelling/expect.txt
  R/process_extract_cmh.R
  R/read_extract_cmh.R
Labels: bug

#630 Fix the casing of the `keytimex` vars.
  .github/actions/spelling/expect.txt
  R/process_extract_ae.R
  R/read_extract_ae.R
Labels: bug

#524 Add targets for the extract processing stage
  .Rbuildignore
  .github/actions/spelling/expect.txt
  .github/workflows/style.yaml
  DESCRIPTION
  R/process_extract_alarms_telecare.R
  R/process_extract_care_home.R
  R/process_extract_home_care.R
  R/process_extract_sds.R
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_care_home.R
  R/process_sc_all_home_care.R
  R/process_sc_all_sds.R
  R/process_tests_sc_ch_episodes.R
  R/process_tests_sc_demographics.R
  R/read_extract_ae.R
  _targets.R
  _targets.yaml
  man/process_extract_alarms_telecare.Rd
  man/process_extract_care_home.Rd
  man/process_extract_home_care.Rd
  man/process_extract_sds.Rd
  man/process_sc_all_alarms_telecare.Rd
  man/process_sc_all_care_home.Rd
  man/process_sc_all_home_care.Rd
  man/process_sc_all_sds.Rd
  man/process_tests_sc_ch_episodes.Rd
  man/process_tests_sc_demographics.Rd
Labels: checking, Processing

#622 Refactor the episode file code
  .github/actions/spelling/expect.txt
  R/run_episode_file.R
  man/correct_cij_vars.Rd
  man/create_cost_inc_dna.Rd
  man/fill_missing_cij_markers.Rd
  man/join_cohort_lookups.Rd
Labels: bug
