Repository Public-Health-Scotland/source-linkage-files, pull requests merged in 2024-02, with the labels that each got.

#894 Remove redundant code
  R/process_tests_district_nursing.R
Labels: Housekeeping

#911 Bug - `high_cc` in demographic cohort showing `NAs` instead of `TRUE/FALSE`
  R/create_demographic_lookup.R
Labels: bug, Priority: High, Mar23-update

#908 Bug - NSUs being assigned psychiatry in the service use cohort
  R/create_service_use_lookup.R
Labels: bug, Priority: High, Mar23-update

#897 Review `check_qtr_format` function
  DESCRIPTION
  R/calculate_stay.R
  R/create_individual_file.R
  R/get_fy_quarter_dates.R
Labels: Priority: High, Mar23-update

#892 Fix targets
  R/aggregate_by_chi.R
  R/create_individual_file.R
  Run_SLF_Files_targets/run_targets_1718.R
  Run_SLF_Files_targets/run_targets_1819.R
  Run_SLF_Files_targets/run_targets_1920.R
  Run_SLF_Files_targets/run_targets_2021.R
  Run_SLF_Files_targets/run_targets_2122.R
  Run_SLF_Files_targets/run_targets_2223.R
  Run_SLF_Files_targets/run_targets_2324.R
  _targets.R
  man/add_all_columns.Rd
  man/aggregate_by_chi.Rd
Labels: On hold, Priority: High, Mar23-update

#899 758 investigate extracts to identify areas of code which can be cut down for processing times
  R/process_sc_all_alarms_telecare.R
  R/process_sc_all_sds.R
Labels: On hold, Priority: High, Mar23-update
